### Authentication.js

### POST CREATE USER SERVICE (Owner)
POST http://localhost:3001/auth/signup
Content-Type: application/json

{
  "name": "Dupont",
  "first_name": "Jean",
  "phone_number": "0612345678",
  "mail": "jean.dupont@test.com",
  "password": "Password123!"
}

### GET USER BY MAIL SERVICE (Owner login)
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "mail": "jean.dupont@test.com",
    "password": "Password123!"
}

### POST CREATE USER SERVICE (Member)
POST http://localhost:3001/auth/signup
Content-Type: application/json

{
  "name": "Durand",
  "first_name": "Alice",
  "phone_number": "0612345679",
  "mail": "alice.durand@test.com",
  "password": "Password123!"
}

### GET USER BY MAIL SERVICE (Member login)
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "mail": "a",
    "password": "a"
}

# ### GET USER BY ID SERVICE
# GET http://localhost:3001/auth/1


### Server.js
#################################################
### CREATE SERVER
#################################################
POST http://localhost:3001/servers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNiZTY1YzUxLTFlZGYtNGMwMC1hZDBhLTAxZmIwNThjNTVkYyIsIm1haWwiOiJqZWFuLmR1cG9udEB0ZXN0LmNvbSIsIm5hbWUiOiJEdXBvbnQiLCJpYXQiOjE3NzMxNTgzNTgsImV4cCI6MTc3MzE3OTk1OH0.s_yHycXNExuhPRoIAKrxJgrWCmdGnuRM6PGs1TWa2jw

{
  "name": "Mon serveur test"
}

#################################################
### GET ALL SERVERS
#################################################
GET http://localhost:3001/servers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZjRkMGQzLWRjMjktNDU0NS04MTc5LTc0MjhiMjcyNGM3NCIsIm1haWwiOiJhIiwibmFtZSI6ImEiLCJpYXQiOjE3NzI3NTAwMDgsImV4cCI6MTc3Mjc3MTYwOH0.t6xT2tqtVjjy7mwGjBXCKFYaExXJ7oh6yj_iymK27mI

#################################################
### GET SERVER BY ID
#################################################
GET http://localhost:3001/servers/1
Authorization: Bearer 

#################################################
### GET SERVER INVITE CODE
#################################################
GET http://localhost:3001/servers/1/inviteCode
Authorization: Bearer 

#################################################
### JOIN SERVER WITH INVITE CODE
#################################################
POST http://localhost:3001/servers/join
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcyZjkyNTZlLTAxYmYtNDY1MC05MDhjLTQ4MzAxMzZmYTE0ZiIsIm1haWwiOiJ6IiwibmFtZSI6InoiLCJpYXQiOjE3NzI3NTEzNTMsImV4cCI6MTc3Mjc3Mjk1M30.3YtKURFtuEth73ei8sL-X0wu0NGqWD62MSM4IDY9I8Q
Content-Type: application/json

{
  "inviteCode": "27551de3d733"
}

#################################################
### GET ALL SERVERS WHERE USER IS MEMBER
#################################################
GET http://localhost:3001/servers/members
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNiZTY1YzUxLTFlZGYtNGMwMC1hZDBhLTAxZmIwNThjNTVkYyIsIm1haWwiOiJqZWFuLmR1cG9udEB0ZXN0LmNvbSIsIm5hbWUiOiJEdXBvbnQiLCJpYXQiOjE3NzMxNTgzNTgsImV4cCI6MTc3MzE3OTk1OH0.s_yHycXNExuhPRoIAKrxJgrWCmdGnuRM6PGs1TWa2jw

#################################################
### GET ALL USERS IN A SERVER
#################################################
GET http://localhost:3001/servers/1/users
Authorization: Bearer 

#################################################
### GET ALL CHANNELS IN A SERVER
#################################################
GET http://localhost:3001/servers/f90a9de2-3c08-4bba-99c5-f17be00e6a49/channels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMxNDNmZGVhLWRjZTktNGNmZC1iNDg0LWNhM2Q4YjdlYzdkMyIsIm1haWwiOiJhIiwibmFtZSI6ImEiLCJpYXQiOjE3NzI3NTA2MTQsImV4cCI6MTc3Mjc3MjIxNH0.b1_ijMpS6yEjN7JE4jAlhN2T_xvHpy7YZ7uDDHaCSPU

#################################################
### CREATE CHANNEL IN SERVER
#################################################
POST http://localhost:3001/servers/f90a9de2-3c08-4bba-99c5-f17be00e6a49/channels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMxNDNmZGVhLWRjZTktNGNmZC1iNDg0LWNhM2Q4YjdlYzdkMyIsIm1haWwiOiJhIiwibmFtZSI6ImEiLCJpYXQiOjE3NzI3NTA2MTQsImV4cCI6MTc3Mjc3MjIxNH0.b1_ijMpS6yEjN7JE4jAlhN2T_xvHpy7YZ7uDDHaCSPU
Content-Type: application/json

{
  "name": "general"
}

#################################################
### UPDATE SERVER NAME
#################################################
PUT http://localhost:3001/servers/1
Authorization: Bearer 
Content-Type: application/json

{
  "name": "Serveur renommé"
}

#################################################
### UPDATE MEMBER ROLE
#################################################
PUT http://localhost:3001/servers/1/members/2
Authorization: Bearer 

{
  "role": "admin"
}

#################################################
### CREATE CHANNEL AS ADMIN
#################################################
POST http://localhost:3001/servers/1/channels
Authorization: Bearer 
Content-Type: application/json

{
  "name": "random"
}

#################################################
### LEAVE SERVER (user courant)
#################################################
DELETE http://localhost:3001/servers/1/leave
Authorization: Bearer 

#################################################
### DELETE SERVER
#################################################
DELETE http://localhost:3001/servers/1
Authorization: Bearer 

### CREATE MESSAGE
POST http://localhost:3001/message
Authorization: Bearer 
Content-Type: application/json

{
  "channelId": "665f1234567890abcdef1234",
  "content": "Bonjour depuis REST"
}

### GET MESSAGES BY CHANNEL
GET http://localhost:3001/message/channel/665f1234567890abcdef1234
Authorization: Bearer 


### Channel.js
#################################################
### GET CHANNEL BY ID
#################################################
GET http://localhost:3001/channels/fc49a4bb-ad69-43cf-8ea5-0919e4a66184
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMxNDNmZGVhLWRjZTktNGNmZC1iNDg0LWNhM2Q4YjdlYzdkMyIsIm1haWwiOiJhIiwibmFtZSI6ImEiLCJpYXQiOjE3NzI3NTIwOTMsImV4cCI6MTc3Mjc3MzY5M30.C5c6iZAJ3z5Y3G8RtKTBtPJtusUy9wqwr6D-X39tRxU

#################################################
### DELETE CHANNEL BY ID
#################################################
DELETE http://localhost:3001/channels/fc49a4bb-ad69-43cf-8ea5-0919e4a66184
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMxNDNmZGVhLWRjZTktNGNmZC1iNDg0LWNhM2Q4YjdlYzdkMyIsIm1haWwiOiJhIiwibmFtZSI6ImEiLCJpYXQiOjE3NzI3NTIwOTMsImV4cCI6MTc3Mjc3MzY5M30.C5c6iZAJ3z5Y3G8RtKTBtPJtusUy9wqwr6D-X39tRxU